name: 'Webhook Event'

on:
  repository_dispatch:
    types:
      - webhook
jobs:
  responding-to-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Print Event info
        run: |
          echo "Event name: $GITHUB_EVENT_NAME"
          echo "Custom type: ${{ github.event.action }}"
          echo "Payload key: ${{ github.event.client_payload.key }}"
