name: Expressions Functions

on:
  push:
    branches:
      - main

jobs:
  expression-functions:
    runs-on: ubuntu-latest
    steps:
      - name: Check if string contains substring
        if: contains ('Devanshu', 'ansh')
        run: echo "'Devanshu' contains the substring 'ansh'"

      - name: Check if string starts with
        if: startsWith('Devanshu', 'Dev')
        run: echo "'Devanshu' starts with 'Dev'"

      - name: Check is string ends with
        if: endsWith('Devanshu', 'shu')
        run: echo "'Devanshu' ends with 'shu'"

      - name: Format and echo string
        run: echo ${{ format('Devanshu {0} {1} {2}', 'Mona', 'the', 'Octocat') }}

      - name: Convert job context to JSON
        run: 'echo Job context in JSON: ${{ toJSON(github.job) }}'

      - name: Parse JSON string
        run: 'echo Parsed JSON: ${{ fromJSON(''"hello":"world"'').hello }}'

      - name: Job succeeded
        if: ${{ success() }}
        run: echo "SUCCESS!"

      - name: Job Failed
        if: ${{ failure() }}
        run: echo "Failure!"
